# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matthew Herman
email: mattherman11@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of tech-related ramblings documenting 
  my attempts at learning to be a better software engineer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.matthewherman.net" # the base hostname & protocol for your site
github_username: mattherman

# Build settings
markdown: kramdown
exclude: [docker-run.sh, README.md]
